# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wand.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wand.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\nwand.proto\"\xc2\x01\n\x04Mask\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\x12\x0c\n\x04wand\x18\x04 \x01(\x08\x12\x14\n\x0c\x61ntialiasing\x18\x05 \x01(\x08\x12\r\n\x05\x65\x64ges\x18\x06 \x01(\x05\x12\x11\n\tthreshold\x18\x07 \x01(\x05\x12\x0c\n\x04mode\x18\x08 \x01(\x05\x12\x11\n\tcriterion\x18\t \x01(\t\x12\x0e\n\x06shape0\x18\n \x01(\x05\x12\x0e\n\x06shape1\x18\x0b \x01(\x05\x12\x0e\n\x06shape2\x18\x0c \x01(\x05\"\x1b\n\nResultMask\x12\r\n\x05image\x18\x01 \x01(\x0c\x32/\n\nmagic_wand\x12!\n\tfind_mask\x12\x05.Mask\x1a\x0b.ResultMask\"\x00\x62\x06proto3')
)




_MASK = _descriptor.Descriptor(
  name='Mask',
  full_name='Mask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='Mask.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='Mask.x', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Mask.y', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wand', full_name='Mask.wand', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='antialiasing', full_name='Mask.antialiasing', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='edges', full_name='Mask.edges', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='threshold', full_name='Mask.threshold', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='Mask.mode', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='criterion', full_name='Mask.criterion', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape0', full_name='Mask.shape0', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape1', full_name='Mask.shape1', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape2', full_name='Mask.shape2', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=209,
)


_RESULTMASK = _descriptor.Descriptor(
  name='ResultMask',
  full_name='ResultMask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='ResultMask.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=238,
)

DESCRIPTOR.message_types_by_name['Mask'] = _MASK
DESCRIPTOR.message_types_by_name['ResultMask'] = _RESULTMASK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Mask = _reflection.GeneratedProtocolMessageType('Mask', (_message.Message,), dict(
  DESCRIPTOR = _MASK,
  __module__ = 'wand_pb2'
  # @@protoc_insertion_point(class_scope:Mask)
  ))
_sym_db.RegisterMessage(Mask)

ResultMask = _reflection.GeneratedProtocolMessageType('ResultMask', (_message.Message,), dict(
  DESCRIPTOR = _RESULTMASK,
  __module__ = 'wand_pb2'
  # @@protoc_insertion_point(class_scope:ResultMask)
  ))
_sym_db.RegisterMessage(ResultMask)



_MAGIC_WAND = _descriptor.ServiceDescriptor(
  name='magic_wand',
  full_name='magic_wand',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=240,
  serialized_end=287,
  methods=[
  _descriptor.MethodDescriptor(
    name='find_mask',
    full_name='magic_wand.find_mask',
    index=0,
    containing_service=None,
    input_type=_MASK,
    output_type=_RESULTMASK,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAGIC_WAND)

DESCRIPTOR.services_by_name['magic_wand'] = _MAGIC_WAND

# @@protoc_insertion_point(module_scope)
