# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import wand_pb2 as wand__pb2


class magic_wandStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.find_mask = channel.unary_unary(
        '/magic_wand/find_mask',
        request_serializer=wand__pb2.Mask.SerializeToString,
        response_deserializer=wand__pb2.ResultMask.FromString,
        )


class magic_wandServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def find_mask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_magic_wandServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'find_mask': grpc.unary_unary_rpc_method_handler(
          servicer.find_mask,
          request_deserializer=wand__pb2.Mask.FromString,
          response_serializer=wand__pb2.ResultMask.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'magic_wand', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
